class UserNotFoundException(Exception):
    pass


class UrlNotFoundException(Exception):
    pass
